<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Главная страница</title>
</head>
<body>
<nav class="navbar navbar-expand navbar-light" style="background-color: white;">
    <div class="container">
        <a class="navbar-brand col-9" href="#"><strong>Questionnaire</strong></a>
        <a href="/register" class="col-2">
            <button role="button" class="btn btn-primary">Зарегистрироваться</button>
        </a>
        <a href="/login" class="col-1">
            <button role="button" class="btn btn-primary">Войти</button>
        </a>
    </div>
</nav>
<div class="container form-control mt-3 text-center w-50">
    Questionnaire portal - сайт, на котором можно создавать и проходить опросы. Для начала работы войдите в аккаунт или зарегистрируйтесь
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>